# image: java
image: maven:3.6.1
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y graphviz
          - which dot || echo "No dot found??"
          - mvn clean
          - mvn compile
          - mvn test
